services:
  modulos:
    image: img_datapy:latest
    container_name: cnt_datapy
    networks:
      - netbantel
    env_file:
      - /mnt/dockervolumen/mod/conexiones/.env
    environment:
      - PYTHONPATH=/home:/home/conexiones:/home/profit:/home/authenticator:/home/bantel
      - PYTHONUNBUFFERED=1
      - OPENSSL_CONF=/dev/null
    volumes:
      - /mnt/dockervolumen/mod:/home
      - /mnt/wsrv-fstorage-1/:/home
    ports:
      - "8510:8510"

    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  netbantel:
    external: true
