[client]
showSidebarNavigation = false

[theme]
primaryColor="#4285f4"  # Azul característico de Google
backgroundColor="#1e1e1e" # Un gris muy oscuro, casi negro
secondaryBackgroundColor="#2a2a2a" # Un gris ligeramente más claro para los paneles
textColor="#e0e0e0" # Un gris claro para el texto principal
font="sans serif"